[workspace]
resolver = "2"

members = ["tapo", "tapo-py"]

[workspace.dependencies]
chrono = { version = "0.4.25", default-features = false }
pyo3 = { version = "0.21" }
tokio = { version = "1.37", default-features = false }
