[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
skip_core_tasks = true

[tasks.format]
command = "cargo"
args = ["fmt", "--verbose", "--", "--check"]

[tasks.check]
command = "cargo"
args = ["check", "--verbose"]

[tasks.check-doc]
env = { "RUSTDOCFLAGS" = "-D warnings" }
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--verbose", "--", "-D", "warnings"]

[tasks.test]
command = "cargo"
args = ["test", "--verbose"]

[tasks.ci-flow]
dependencies = ["format", "check", "check-doc", "clippy", "test"]
